default_platform(:ios)

platform :ios do
  desc "Run unit test and swiftlint"
  lane :metrics do
    derived_data_path = "./DerivedData"
    
    scan(
      workspace: "./A-Commerce.xcworkspace",
      scheme: "A-Commerce", 
      devices: "iPhone 11",

      clean: true,
      code_coverage: true,

      derived_data_path: derived_data_path
    )

    slather(
      workspace: './A-Commerce.xcworkspace',
      proj: "./A-Commerce.xcodeproj",
      scheme: "A-Commerce",
    
      github: true,
      sonarqube_xml: true, 
      html: true,
      
      build_directory: derived_data_path, 
      output_directory: "./sonar-reports", 
      
      ignore: ["Pods/*", "ThirdParty/*", "Frameworks/*"]
    )

    swiftlint(
      output_file: "./sonar-reports/swiftlint.txt", 
      ignore_exit_status: true
    )
  end
end
